version: "2.1"
services:
  validator:
    image: w3villa/sawtooth:latest
    container_name: validator
    working_dir: /app/
    ports:
      - "4004:4004"
      - "8800:8800"
      - "5050:5050"
    command: "bash -c \"\
        sawtooth keygen --force && \
        sawadm keygen --force && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=PoET \
          sawtooth.consensus.algorithm.version=0.1 \
          sawtooth.poet.report_public_key_pem=\
          \\\"$$(cat /etc/sawtooth/simulator_rk_pub.pem)\\\" \
          sawtooth.poet.valid_enclave_measurements=$$(poet enclave measurement) \
          sawtooth.poet.valid_enclave_basenames=$$(poet enclave basename) \
          -o config.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
             sawtooth.poet.target_wait_time=5 \
             sawtooth.poet.initial_wait_time=25 \
             sawtooth.publisher.max_batches_per_block=100 \
          -o poet-settings.batch && \
        sawset genesis \
            --key ~/.sawtooth/keys/root.priv \ 
            -o config-genesis.batch && \
        sawtooth-validator -vv \
          --bind network:tcp://0.0.0.0:8800 \
          --bind component:tcp://0.0.0.0:4004 \
          --bind consensus:tcp://0.0.0.0:5050 \
          --peering static \
          --endpoint tcp:///bcd1.kleinschmidt.com:8800 \
          --scheduler parallel \
          --network-auth trust
    \""
    # stop_signal: SIGKILL
  rest-api:
    image: w3villa/sawtooth:latest
    container_name: sawtooth-rest-api
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: |
      bash -c " 
      sawtooth-rest-api -vv \
      --connect tcp:///bcd1.kleinschmidt.com:4004 \
      --bind 0.0.0.0:8008 
      "
    # stop_signal: SIGKILL  
  settings-tp:
    image: w3villa/sawtooth:latest
    container_name: sawtooth-settings-tp
    ports:
      - "4004"
    depends_on:
      - validator
      - rest-api  
    command: |
      bash -c "
      settings-tp -v -C tcp:///bcd1.kleinschmidt.com:4004
      "
    stop_signal: SIGKILL
  intkey-tp:
    image: w3villa/sawtooth:latest
    container_name: sawtooth-intkey-tp
    ports:
      - "4004"
    depends_on:
      - validator
      - rest-api  
    command: |
      bash -c "
      intkey-tp-python -v -C tcp:///bcd1.kleinschmidt.com:4004
      "
    # stop_signal: SIGKILL
  xo-tp:
    image: w3villa/sawtooth:latest
    container_name: sawtooth-xo-tp
    ports:
      - "4004"
    depends_on:
      - validator
      - rest-api  
    command: |
      bash -c "
      xo-tp-python -vv -C tcp:///bcd1.kleinschmidt.com:4004
      "
    # stop_signal: SIGKILL
  poet-validator-registry-tp:
    image: w3villa/sawtooth:latest
    container_name: poet-validator
    ports:
      - "4004"
    depends_on:
      - validator
      - rest-api  
    command: |
      bash -c "
      poet-validator-registry-tp -v -C tcp:///bcd1.kleinschmidt.com:4004
      "
    # stop_signal: SIGKILL
  poet-engine:
    image: w3villa/sawtooth:latest
    container_name: poet-engine
    depends_on:
      - validator
      - rest-api
    command: |
      bash -c "
      poet-engine -vv -C tcp:///bcd1.kleinschmidt.com:5050 --component tcp:///bcd1.kleinschmidt.com:4004
      "
    # stop_signal: SIGKILL
